# E - Gyroid

filename: 'E'

res: 5
couponStandard: D638
centerLengthScale: 1.2126 # transition length scale multiplier
blurRadius: 6 # mm -- transition region width * 1/2
materialStep: 0.2 # material step size of final result

gyroidEnable: True

gyroidType: 1 # 1 - gyroid, 2 - p-surface, 3 - d-surface, 4 - FRD
gyroidMaxDilate: 2
gyroidMaxErode: 1



