# K - large fibers

filename: 'K'

res: 5
couponStandard: D638
centerLengthScale: 1.0000 # transition length scale multiplier
blurRadius: 6 # mm -- transition region width * 1/2
materialStep: 0.2 # material step size of final result

latticeEnable: True

latticeElementFile: 'lattice_element_5_30x30'
minRadius: 2 # min radius that results in a printable structure
maxRadius: 5 # max radius that results in a viable lattice element