# J - small fibers

filename: 'J'

res: 5
couponStandard: D638
centerLengthScale: 1.19061976381033 # transition length scale multiplier
blurRadius: 6 # mm -- transition region width * 1/2
materialStep: 0.2 # material step size of final result

latticeEnable: True

latticeElementFile: 'lattice_element_4_15x15'
minRadius: 0 # min radius that results in a printable structure
maxRadius: 2 # max radius that results in a viable lattice element



