# H - plus

filename: 'H'

res: 5
couponStandard: D638
centerLengthScale: 1.0813 # transition length scale multiplier
blurRadius: 6 # mm -- transition region width * 1/2
materialStep: 0.2 # material step size of final result

latticeEnable: True

latticeElementFile: 'lattice_element_2_15x15'
minRadius: 1 # min radius that results in a printable structure
maxRadius: 5 # max radius that results in a viable lattice element



