# A - Control

filename: 'A'

res: 5
couponStandard: D638
centerLengthScale: 1.0000 # transition length scale multiplier
blurRadius: 6 # mm -- transition region width * 1/2
materialStep: 0.2 # material step size of final result



