# D - 2D Dither

filename: 'D'

res: 5
couponStandard: D638
centerLengthScale: 1.0000 # transition length scale multiplier
blurRadius: 6 # mm -- transition region width * 1/2
materialStep: 0.2 # material step size of final result

ditherEnable: True

ditherType: 2 # 1 - xyz, 2 - xy, 3 - y
processingRes: 8 # voxels per processed voxel



